{% set name = "rocm-smi" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROC-smi/archive/roc-{{ version }}.tar.gz
  sha256: 8ed448491db59b0d586dff7475ec8c40b8fca2063c480f31c721f64b22a44326

build:
  number: 0
  skip: True  # [not linux]
  script:
    - mkdir -p $PREFIX/bin
    - cp rocm_smi.py $PREFIX/bin/rocm_smi.py
    - chmod +x $PREFIX/bin/rocm_smi.py
    - ln -s $PREFIX/bin/rocm_smi.py $PREFIX/bin/rocm-smi

test:
  commands:
    - test -f $PREFIX/bin/rocm-smi

about:
  home: https://github.com/RadeonOpenCompute/ROC-smi
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'ROC System Management Interface'

extra:
  recipe-maintainers:
    - isuruf
